# Beginner tutorial on PyTorch an ANN - Articficial Neural Network

In [20]:
import torch
import numpy as np
import sys

In [21]:
# deep learning can use CPU or GPU
torch.cuda.is_available()

False

In [22]:
# torch.device('cuda0')
device = torch.device('cpu')
device

device(type='cpu')

## Let's start

In [28]:


# <img src = 'japan.png'/>

In [ ]:
'''
m = 5
n = 3 --> temp, rain, humidity
y = yield of apples and orange
'''

'\nm = 5\nn = 3 --> temp, rain, humidity\ny = yield of apples and orange\n'

## Step 1 . Specify X and y

In [ ]:
# Input (temp, rainfall, humidity)
X_train = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
y_train = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

In [ ]:
# have to convert numpy to torch tesors
# torch tensors are simple numpy version of pytorch
inputs = torch.from_numpy(X_train)
targets = torch.from_numpy(y_train)

# torch.Tensor
type(inputs), type(targets) 
'''
torch inclued gradient descent for every steps
'''

inputs.shape, targets.shape
inputs.size(), targets.size()

(torch.Size([15, 3]), torch.Size([15, 2]))

## 2. Dataloaders

Remember in ML, we have to do the batch learning outselve, like mini-batch, stochastic batch. PyTorch has a class called DataLoaders that automatically do this for you.

It's optional whether you wanna use it or just use it - don't reinvent the wheel

In [24]:
# define a dataset so that dataloaders understand
from torch.utils.data import TensorDataset

train_dataset = TensorDataset (inputs, targets)

train_dataset[0]

(tensor([73., 67., 43.]), tensor([56., 70.]))

In [25]:
from torch.utils.data import DataLoader

batch_size = 3 # for no reason - here i am using  a mini-batch of size 3

train_dl = DataLoader (train_dataset, batch_size, shuffle=False) # you should use Shuffle = True

In [26]:
for x, y in train_dl:
    print("------new batch--------")
    print(x) # this will give you batch_size of x, e.g. 3 sets of x
    print(y) # this will give you batch_size of y, e.g. 3 sets of y

------new batch--------
tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.]])
------new batch--------
tensor([[102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.]])
tensor([[ 22.,  37.],
        [103., 119.],
        [ 56.,  70.]])
------new batch--------
tensor([[ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.]])
tensor([[ 81., 101.],
        [119., 133.],
        [ 22.,  37.]])
------new batch--------
tensor([[69., 96., 70.],
        [73., 67., 43.],
        [91., 88., 64.]])
tensor([[103., 119.],
        [ 56.,  70.],
        [ 81., 101.]])
------new batch--------
tensor([[ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## 3. Define some layers

don't be confuse about layers. it's simply matrix multiplication. It's true until now.

In [30]:
import torch.nn as nn  # nn ==> neural networt

In [32]:
# define Linear Layer: 3 is the incoming features and 2 is the output feature
some_random_layer = nn.Linear(3,2)

In [36]:
# matrix --> randomly initialize --> using standardization methods
print (some_random_layer.weight)
print (some_random_layer.weight.shape)
print (some_random_layer.bias)
print (some_random_layer.bias.shape)

Parameter containing:
tensor([[ 0.4134, -0.2677,  0.4778],
        [ 0.0888, -0.5604,  0.3382]], requires_grad=True)
torch.Size([2, 3])
Parameter containing:
tensor([-0.3487, -0.0836], requires_grad=True)
torch.Size([2])


In [37]:
outputs = some_random_layer (inputs) # do matrix multiplication of incoming layer
# input = (15,3) @ (3,2) = (15,2)

outputs.shape

torch.Size([15, 2])

In [38]:
# how do chatgpt count their number of parameters - 175b parameters

# count their number of parameters
# some_random_layer.parameters()

<generator object Module.parameters at 0x11fbcd620>

In [41]:
# count their number of parameters
total_num_of_param = 0
for param in some_random_layer.parameters():
    print (param)
    total_num_of_param += param.numel()

print (f"total number of parameter=", total_num_of_param)

Parameter containing:
tensor([[ 0.4134, -0.2677,  0.4778],
        [ 0.0888, -0.5604,  0.3382]], requires_grad=True)
Parameter containing:
tensor([-0.3487, -0.0836], requires_grad=True)
total number of parameter= 8
